name: andreas
description: Een app ten behoeve van scoutingleden, ouders en vrijwilligers

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  firebase_auth: ^0.15.3
  flutter:
    sdk: flutter
  flutter_svg: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Snorelia
      fonts:
        - asset: fonts/Snorelia-Regular.otf
